# fly.toml app configuration file generated for citadel-backend on 2024-01-23T12:18:58-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "citadel-backend"
primary_region = "sea"

[http_service]
  internal_port = 61440
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="ex_library"
  destination="/data/"
