
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async initClient(libraryPath: string) : Promise<Result<CalibreClientConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_client", { libraryPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryIsPathValidLibrary(libraryRoot: string) : Promise<boolean> {
    return await TAURI_INVOKE("clb_query_is_path_valid_library", { libraryRoot });
},
async clbCmdCreateLibrary(libraryRoot: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_create_library", { libraryRoot }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryListAllBooks() : Promise<Result<LibraryBook[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_list_all_books") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQuerySearchBooks(query: string) : Promise<Result<LibraryBook[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_search_books", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryBooks(query: LibraryBookQuery) : Promise<Result<LibraryBookPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_books", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryIsFileImportable(pathToFile: string) : Promise<ImportableFile | null> {
    return await TAURI_INVOKE("clb_query_is_file_importable", { pathToFile });
},
async clbQueryImportableFileMetadata(file: ImportableFile) : Promise<ImportableBookMetadata | null> {
    return await TAURI_INVOKE("clb_query_importable_file_metadata", { file });
},
async clbQueryListAllFiletypes() : Promise<([string, string])[]> {
    return await TAURI_INVOKE("clb_query_list_all_filetypes");
},
async clbQueryListSeries() : Promise<Result<LibrarySeries[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_list_series") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdCreateBook(md: ImportableBookMetadata) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_create_book", { md }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdUpdateBook(bookId: string, updates: BookUpdate) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_update_book", { bookId, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdUpsertBookIdentifier(bookId: string, label: string, value: string, existingId: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_upsert_book_identifier", { bookId, label, value, existingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdDeleteBookIdentifier(bookId: string, identifierId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_delete_book_identifier", { bookId, identifierId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdSetBookCoverFromUrl(bookId: string, imageUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_set_book_cover_from_url", { bookId, imageUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryListCustomColumns() : Promise<Result<CustomColumnDef[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_list_custom_columns") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryGetCustomValuesForBook(bookId: string) : Promise<Result<BookCustomValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_get_custom_values_for_book", { bookId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdSetCustomValue(bookId: string, columnId: number, value: CustomValueDto | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_set_custom_value", { bookId, columnId, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbQueryListAllAuthors() : Promise<Result<LibraryAuthor[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_query_list_all_authors") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdCreateAuthors(newAuthors: NewAuthor[]) : Promise<Result<LibraryAuthor[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_create_authors", { newAuthors }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdUpdateAuthor(authorId: string, updates: AuthorUpdate) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_update_author", { authorId, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdDeleteAuthor(authorId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_delete_author", { authorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testHardcoverConnection(apiKey: string) : Promise<Result<HardcoverApiStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_hardcover_connection", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchHardcoverMetadataByIsbn(apiKey: string, isbn: string) : Promise<Result<HardcoverBookMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_hardcover_metadata_by_isbn", { apiKey, isbn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchHardcoverMetadataByBookId(apiKey: string, hardcoverId: number) : Promise<Result<HardcoverBookMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_hardcover_metadata_by_book_id", { apiKey, hardcoverId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHardcoverBooks(apiKey: string, query: string) : Promise<Result<HardcoverSearchResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_hardcover_books", { apiKey, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdCheckForUpdates() : Promise<Result<UpdateCheckResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdInstallUpdateIfAvailable() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clb_cmd_install_update_if_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clbCmdOpenSettings() : Promise<void> {
    await TAURI_INVOKE("clb_cmd_open_settings");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthorUpdate = { full_name: string | null; sortable_name: string | null; external_url: string | null }
/**
 * One book's value for one custom column.
 */
export type BookCustomValue = { column_id: number; value: CustomValueDto }
export type BookFile = { Local: LocalFile } | { Remote: RemoteFile }
export type BookSortOrder = "TitleAsc" | "TitleDesc" | "AuthorAsc" | "AuthorDesc"
export type BookUpdate = { author_id_list: string[] | null; tag_list: string[] | null; title: string | null; timestamp: string | null; publication_date: string | null; is_read: boolean | null; description: string | null; 
/**
 * An empty (or whitespace) name unlinks the book from its series;
 * `None` leaves it unchanged.
 */
series: string | null; series_index: number | null }
export type CalibreClientConfig = { library_path: string }
/**
 * A custom column definition, as exposed to the frontend.
 */
export type CustomColumnDef = { column_id: number;
/**
 * Lookup name, e.g. `read` (Calibre exposes it as `#read`).
 */
label: string;
/**
 * Human-readable heading, e.g. `Read`.
 */
name: string;
/**
 * Raw Calibre datatype string, e.g. `bool`, `text`, `enumeration`.
 */
datatype: string; is_multiple: boolean; editable: boolean;
/**
 * Whether reading and writing values of this column is supported.
 */
supported: boolean;
/**
 * Allowed values for enumeration columns. Empty for other datatypes.
 */
enum_values: string[] }
/**
 * A custom-column value crossing the Tauri boundary.
 *
 * Mirrors `libcalibre::CustomValue`, except datetimes travel as RFC3339
 * strings and integers as `i32` (specta cannot export `i64` without bigint
 * support).
 */
export type CustomValueDto = { Bool: boolean } | { Int: number } | { Float: number } | { Text: string } | { TextMultiple: string[] } |
/**
 * RFC3339 datetime string, e.g. `2024-01-15T10:30:00+00:00`.
 */
{ Datetime: string } | { Enumeration: string }
export type HardcoverApiStatus = { is_valid: boolean; message: string }
export type HardcoverBookMetadata = { title: string; description: string | null; image_url: string | null; isbn: string | null; release_year: number | null; hardcover_id: number | null; slug: string | null }
export type HardcoverSearchResult = { title: string; description: string | null; image_url: string | null; isbn: string | null; release_year: number | null; hardcover_id: number; slug: string | null; authors: string[] }
/**
 * Book identifiers, such as ISBN, DOI, Google Books ID, etc.
 */
export type Identifier = { id: number; label: string; value: string }
/**
 * Represents metadata for pre-import books, which have a very loose structure.
 */
export type ImportableBookMetadata = { file_type: ImportableBookType; 
/**
 * The title of the book, if one is available, or the name of the file to import.
 */
title: string; 
/**
 * The list of authors of the book, if available. Some books may not be formatted correctly,
 * and will have no authors, or all author names will be one string separated by "," or ";".
 */
author_names: string[] | null; identifier: string | null; publisher: string | null; language: string | null; tags: string[]; 
/**
 * Path of the file to import.
 */
path: string; publication_date: string | null; 
/**
 * True if a cover image can be extracted from the file at `path`.
 */
file_contains_cover: boolean }
export type ImportableBookType = "Epub" | "Pdf" | "Mobi" | "Text"
export type ImportableFile = { path: string }
export type LibraryAuthor = { id: string; name: string; sortable_name: string }
export type LibraryBook = { id: string; uuid: string | null; title: string; author_list: LibraryAuthor[]; tag_list: string[]; sortable_title: string | null; file_list: BookFile[]; cover_image: LocalOrRemoteUrl | null; identifier_list: Identifier[]; description: string | null; is_read: boolean; series: string | null; series_index: number | null }
export type LibraryBookPage = { items: LibraryBook[];
/**
 * Total number of books matching the filters, ignoring limit/offset.
 */
total: number }
export type LibraryBookQuery = { 
/**
 * Substring match across title, author names, and series names.
 * `None` or empty text matches all books.
 */
text: string | null; author_id: string | null; series_id: number | null; hide_read: boolean; sort: BookSortOrder; 
/**
 * Page size. `None` returns all matches.
 */
limit: number | null; offset: number }
/**
 * One series in the library. `id` is what [`LibraryBookQuery::series_id`]
 * filters on; the frontend otherwise only ever sees series names.
 */
export type LibrarySeries = { id: number; name: string; book_count: number }
export type LocalFile = { 
/**
 * The absolute path to the file, including extension.
 */
path: string; 
/**
 * The MIME type of the file. Common values are `application/pdf` and `application/epub+zip`.
 */
mime_type: string }
export type LocalOrRemote = "Local" | "Remote"
export type LocalOrRemoteUrl = { kind: LocalOrRemote; url: string; local_path: string | null }
export type NewAuthor = { name: string; sortable_name: string | null }
export type RemoteFile = { url: string }
export type UpdateCheckResult = { has_update: boolean; version: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
